/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IndieProjectFunding } from "./IndieProjectFunding";
export * as factories from "./factories";
export { IndieProjectFunding__factory } from "./factories/IndieProjectFunding__factory";
